### PR TITLE
Intergration with Open Liberty

### PR DESCRIPTION
**Pull request by Kubik42**
Hi Arun. Here is the open liberty demonstration for your microservices that you talked about with Emily at DevNexus.

Overall, I added three new profiles to each service pom. One for running the service with wildfly like before, one to run the service in open liberty, and for building docker images for open liberty.

The services can be run the same way as before, with an addition of a profile name:

```
mvn -pl <service> <goals> -P <profile>
```

For example, to run the `greeting` service on wildfly as before:

```
mvn -pl greeting wildfly-swarm:run -P wildfly
```

To run the same service on open liberty:

```
mvn -pl greeting install liberty:start-server -P openliberty
```

Additionally, I also made it so that all three services can be started at the same time in open liberty from the parent projec. This is done using the `openliberty` profile in the parent pom.

```
mvn install liberty:start-server -P openliberty
```

Just a heads up, it might be worth running the `clean` goal when switching from wildfly to open liberty:

```
mvn -pl <service> clean -P <profile>
```

To stop a service that is running in open liberty:

```
mvn -pl <service> liberty:stop-server -P openliberty
# or for all services
mvn liberty:stop-server -P openliberty
```

I also added a new profile called `docker-openliberty` for building docker images with open liberty into each child pom. Each image will have the name `arungupta/<service>:openliberty`. So, the same as you had before but with a different tag. I also added a new docker-compose yaml to `app/docker` for openliberty stuff. You can deploy your stack the same as before, just point to the second yaml:

```
docker stack deploy --compose-file docker-compose-openliberty.yaml myapp
```

Justifications for code changes:

- `web.xml` files need an extra slash in the url pattern as defined in the servlet spec otherwise the servlet filter may not filter request properly.
- `NameMessageBodyWriter` class needed to be added to the `MyApplication` class to be visible.
- I also made some suggestive changed to the `WebappController` class. I noticed that you set the `id` parameter to `1` in case it wasn't passed in. You can actually define a default value for it using the `@DefaultValue` annotation. I can change this back if you prefer the old approach.

Please let us know if you run into any issues or if you want anything changed. :)

### CODE REVIEW

**Comment by Kubik42** [comment]
@yeekangc  @evelinec

**Comment by arun-gupta** [comment]
Thanks for the PR!

Per https://github.com/aws-samples/aws-microservices-deploy-options/issues/196, the source code for all the services is moving to three different repos. The PR will have to be reissued against those repos once the migration is complete.

**Comment by arun-gupta** [comment]
The services have now been refactored as explained at https://github.com/aws-samples/aws-microservices-deploy-options/pull/197.

Will close this PR. Please send another PR for the repos mentioned in #197.

**Comment by yeekangc** [comment]
Thank you, @arun-gupta.  We will do that.

**Pull request closed without merging**
